<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $catEnterprise = Category::where('slug', 'enterprise-software')->first();
        $catEcom = Category::where('slug', 'ecommerce-solutions')->first();
        $catHr = Category::where('slug', 'hr-systems')->first();
        $catLms = Category::where('slug', 'learning-management')->first();

        // Product 1: Riof ERP
        Product::create([
            'slug' => 'riof-erp',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Riof ERP',
            'name_ar' => 'ريوف ERP',
            'description_en' => 'Comprehensive ERP system tailored for enterprise digital management. Includes core modules: Financial Accounting, Inventory Control, Supply Chain, Procurement, CRM, Analytics & BI, Role-Based Access Control (RBAC), and Audit Logging. Fully optimized for Search Engines with optimized structured data, meta tags, keyword targeting, and clean URLs.',
            'description_ar' => 'نظام تخطيط موارد المؤسسات (ERP) شامل مصمم للإدارة الرقمية للمؤسسات. يشمل الوحدات الأساسية: المحاسبة المالية، مراقبة المخزون، سلسلة التوريد، المشتريات، إدارة علاقات العملاء، التحليلات وذكاء الأعمال، التحكم في الوصول القائم على الأدوار، وتسجيل التدقيق. محسن بالكامل لمحركات البحث.',
            'price_usd' => 120000.00,
            'price_sar' => 450000.00,
            'features_en' => json_encode([
                'Financial Accounting & General Ledger',
                'Inventory Control & Warehouse Management',
                'Supply Chain & Procurement Management',
                'Customer Relationship Management (CRM)',
                'Analytics & Business Intelligence',
                'Role-Based Access Control (RBAC)',
                'Audit Logging & Compliance',
                'Multi-Currency & Multi-Language Support',
            ]),
            'features_ar' => json_encode([
                'المحاسبة المالية ودليل الحسابات العام',
                'مراقبة المخزون وإدارة المستودعات',
                'إدارة سلسلة التوريد والمشتريات',
                'إدارة علاقات العملاء',
                'التحليلات وذكاء الأعمال',
                'التحكم في الوصول القائم على الأدوار',
                'تسجيل التدقيق والامتثال',
                'دعم العملات المتعددة واللغات المتعددة',
            ]),
            'seo_title_en' => 'Riof ERP | Enterprise Digital Management System',
            'seo_title_ar' => 'ريوف ERP | نظام الإدارة الرقمية للمؤسسات',
            'seo_description_en' => 'Riof ERP is a comprehensive enterprise resource planning system with financial accounting, inventory, CRM, BI analytics, and RBAC. Optimized for digital enterprise management.',
            'seo_description_ar' => 'ريوف ERP هو نظام شامل لتخطيط موارد المؤسسات مع المحاسبة المالية والمخزون وإدارة علاقات العملاء وتحليلات ذكاء الأعمال والتحكم في الوصول.',
            'seo_keywords_en' => 'ERP, enterprise software, digital management, financial accounting, inventory control, CRM, BI analytics, RBAC, business management',
            'seo_keywords_ar' => 'ERP, برامج المؤسسات, الإدارة الرقمية, المحاسبة المالية, مراقبة المخزون, إدارة علاقات العملاء, تحليلات الأعمال',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 1,
        ]);

        // Product 2: Riof Store v-1
        Product::create([
            'slug' => 'riof-store-v1',
            'type' => 'digital',
            'category_id' => $catEcom?->id,
            'name_en' => 'Riof Store v-1',
            'name_ar' => 'ريوف ستور v-1',
            'description_en' => 'Riof Store v-1 is a Laravel Multi-Vendor eCommerce CMS. Launch a marketplace that feels structured from day one, not stitched together after launch. Riof Store gives commerce teams a practical foundation for running single-store or multi-vendor operations with connected storefront, vendor, and admin workflows. It is designed to support growth while keeping catalogue, checkout, and order flow manageable. Features: Advanced Mega Menu Builder, Ajax-based tasks, Gift Cards, Guest Checkout, Digital & Physical Product architecture, Home Page Builder, Unlimited Email Templates, Dynamic Sliders, Multi-Language (170+ languages), Multi-Currency, Order Management, Brands, Verified Reviews, Product Deals, Wishlists, Dynamic Coupons, Multi-Level Categories, Category-wise Commission Setup, Product Ratings, Gallery with Zoom, Social Login, Google reCAPTCHA, Newsletters, Product Attributes, Enterprise Security, Product Comparison, GA4 Analytics & Facebook Pixel integration, PWA Ready, One-Click Demo Import, Custom SMS Gateway integration, Messenger integration, Currency Decimal Control, Blog Engine, Product Video, Quick View, SKU Management, Unlimited Variants, Dynamic Tax/GST Calculation, Dynamic Filters, Invoice PDF Generation, Role & Permissions Engine, Up-sells & Cross-sells, Low Inventory Alerts, RTL Support, W3C Valid Markup, Bootstrap 5 UI framework.',
            'description_ar' => 'ريوف ستور v-1 هو نظام إدارة محتوى تجارة إلكترونية متعدد البائعين مبني على Laravel. أطلق سوقاً إلكترونياً منظمًا من اليوم الأول. يمنح ريوف ستور فرق التجارة أساسًا عمليًا لإدارة عمليات متجر واحد أو متعدد البائعين مع سير عمل متصل للواجهة الأمامية والبائعين والإدارة. يدعم النمو مع الحفاظ على سهولة إدارة الكتالوج وعربة التسوق والطلبات. الميزات: منشئ قوائم متقدم، مهام Ajax، بطاقات هدايا، شراء كضيف، دعم المنتجات الرقمية والمادية، منشئ صفحات رئيسية، قوالب بريد إلكتروني غير محدودة، شرائح ديناميكية، دعم 170+ لغة، عملات متعددة، إدارة الطلبات، العلامات التجارية، مراجعات موثقة، صفقات المنتجات، قوائم الرغبات، كوبونات ديناميكية، تصنيفات متعددة المستويات، عمولة حسب التصنيف، معرض مع تكبير، تسجيل اجتماعي، reCAPTCHA، النشرات البريدية، سمات المنتج، أمان مؤسسي، مقارنة المنتجات، تحليلات GA4 وفيسبوك بيكسل، PWA، استيراد تجريبي بنقرة واحدة، Gateway SMS مخصص، تكامل المراسلة، التحكم في الكسور العشرية للعملة، محرك مدونة، فيديو المنتج، عرض سريع، إدارة SKU، متغيرات غير محدودة، حساب ضريبة ديناميكي، فلاتر ديناميكية، توليد فواتير PDF، محرك الأدوار والصلاحيات، البيع الإضافي والبيع المتبادل، تنبيهات المخزون المنخفض، دعم RTL، Bootstrap 5.',
            'price_usd' => 80000.00,
            'price_sar' => 300000.00,
            'features_en' => json_encode([
                'Marketplace-ready multi-vendor architecture',
                'Vendor onboarding & seller-side management workflows',
                'Product catalogue control with browsing & cart flow',
                'Checkout & order lifecycle handling',
                'Promotion and discount tooling',
                'Admin controls for marketplace governance',
                'Advanced Mega Menu Builder',
                'Guest Checkout support',
                'Digital & Physical Product support',
                'Multi-Language (170+ languages)',
                'Multi-Currency with decimal control',
                'GA4 Analytics & Facebook Pixel integration',
                'PWA Ready',
                'Role & Permissions Engine',
                'RTL Support & Bootstrap 5 UI',
            ]),
            'features_ar' => json_encode([
                'هندسة سوق متعدد البائعين جاهزة',
                'سير عمل تأهيل البائعين وإدارة البائعين',
                'التحكم في كتالوج المنتجات مع التصفح وعربة التسوق',
                'معالجة الطلبات ودورة حياة الطلب',
                'أدوات العروض والخصم',
                'ضوابط إدارية لحوكمة السوق',
                'منشئ قوائم متقدم',
                'دعم الشراء كضيف',
                'دعم المنتجات الرقمية والمادية',
                'دعم 170+ لغة',
                'عملات متعددة مع التحكم في الكسور العشرية',
                'تكامل تحليلات GA4 وفيسبوك بيكسل',
                'جاهز لتقنية PWA',
                'محرك الأدوار والصلاحيات',
                'دعم RTL وواجهة Bootstrap 5',
            ]),
            'seo_title_en' => 'Riof Store v-1 | Multi-Vendor eCommerce CMS | Laravel Marketplace',
            'seo_title_ar' => 'ريوف ستور v-1 | نظام تجارة إلكترونية متعدد البائعين | سوق Laravel',
            'seo_description_en' => 'Riof Store v-1 is a Laravel Multi-Vendor eCommerce CMS. Launch a structured marketplace with vendor management, multi-currency, multi-language, PWA, GA4 analytics, and RTL support.',
            'seo_description_ar' => 'ريوف ستور v-1 هو نظام إدارة محتوى تجارة إلكترونية متعدد البائعين مبني على Laravel. أطلق سوقاً إلكترونياً منظماً مع إدارة البائعين والعملات المتعددة واللغات المتعددة.',
            'seo_keywords_en' => 'multi-vendor ecommerce, laravel marketplace, cms, online store, digital marketplace, ecommerce platform, multi-currency, multi-language',
            'seo_keywords_ar' => 'تجارة إلكترونية متعددة البائعين, سوق Laravel, نظام إدارة محتوى, متجر إلكتروني, سوق رقمي, منصة تجارة إلكترونية',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 2,
        ]);

        // Product 3: Riof HR v-1
        Product::create([
            'slug' => 'riof-hr-v1',
            'type' => 'digital',
            'category_id' => $catHr?->id,
            'name_en' => 'Riof HR v-1',
            'name_ar' => 'ريوف HR v-1',
            'description_en' => 'Comprehensive Human Resources & Payroll Management System. Core HR Features: Employee Self-Service (ESS) portal, Attendance & Leave Management, Biometric Device Integration support, Payroll & Payslip Generation, Department/Role Management, HR Analytics & Performance Reviews, Recruitment & Onboarding Workflows, Document Management, Expense Claims, and Activity Logging.',
            'description_ar' => 'نظام شامل لإدارة الموارد البشرية والرواتب. الميزات الأساسية: بوابة الخدمة الذاتية للموظفين، إدارة الحضور والإجازات، دعم تكامل أجهزة البصمة، إنشاء الرواتب وقسائم الراتب، إدارة الأقسام والأدوار، تحليلات الموارد البشرية ومراجعات الأداء، سير عمل التوظيف والتعيين، إدارة المستندات، مطالبات المصروفات، وتسجيل النشاطات.',
            'price_usd' => 35000.00,
            'price_sar' => 131250.00,
            'features_en' => json_encode([
                'Employee Self-Service (ESS) Portal',
                'Attendance & Leave Management',
                'Biometric Device Integration',
                'Payroll & Payslip Generation',
                'Department & Role Management',
                'HR Analytics & Performance Reviews',
                'Recruitment & Onboarding Workflows',
                'Document Management System',
                'Expense Claims Management',
                'Activity Logging & Audit Trail',
            ]),
            'features_ar' => json_encode([
                'بوابة الخدمة الذاتية للموظفين',
                'إدارة الحضور والإجازات',
                'تكامل أجهزة البصمة',
                'إنشاء الرواتب وقسائم الراتب',
                'إدارة الأقسام والأدوار',
                'تحليلات الموارد البشرية ومراجعات الأداء',
                'سير عمل التوظيف والتعيين',
                'نظام إدارة المستندات',
                'إدارة مطالبات المصروفات',
                'تسجيل النشاطات ومسار التدقيق',
            ]),
            'seo_title_en' => 'Riof HR v-1 | Human Resources & Payroll Management System',
            'seo_title_ar' => 'ريوف HR v-1 | نظام إدارة الموارد البشرية والرواتب',
            'seo_description_en' => 'Riof HR v-1 is a comprehensive HR and payroll management system with ESS portal, attendance management, biometric integration, payroll generation, and HR analytics.',
            'seo_description_ar' => 'ريوف HR v-1 هو نظام شامل لإدارة الموارد البشرية والرواتب مع بوابة الخدمة الذاتية وإدارة الحضور وتكامل البصمة وإنشاء الرواتب وتحليلات الموارد البشرية.',
            'seo_keywords_en' => 'HR software, payroll system, human resources management, employee self-service, attendance management, biometric integration, payslip generation',
            'seo_keywords_ar' => 'برامج الموارد البشرية, نظام الرواتب, إدارة الموارد البشرية, خدمة ذاتية للموظفين, إدارة الحضور, تكامل البصمة, إنشاء قسائم الراتب',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 3,
        ]);

        // Product 4: Learning Management System CMS
        Product::create([
            'slug' => 'learning-management-system-cms',
            'type' => 'digital',
            'category_id' => $catLms?->id,
            'name_en' => 'Learning Management System CMS',
            'name_ar' => 'نظام إدارة التعلم',
            'description_en' => 'Complete LMS script where you can sell courses and projects without reseller commissions. Keep 100% of profits. Setup multi-instructor marketplaces with Zoom live classes, quizzes, certificates, and drip content. Features: Multi & Public Instructor support, Google Analytics GA4, PWA Ready, Drip Content, Student Login Device Control, Dual-Discount Referral System, Dynamic Certificate Designer, Chapter/Lesson Drag & Drop positioning, Q&A Engine, Student & Instructor Profiles, Database Cart storage, Live Video Previews, Support for YouTube, Vimeo, and Self-hosted MP4s, Video Resume Playback, PDF/Zip Course Downloads, Course Query/Review system, Quizzes, Instructor Bank Payouts, Instant Search, Commission System (Flat, Instructor-wise, Course-wise), Zoom Live Class Integration with Multi-API keys, SEO-friendly plain URLs, RTL Support, Automatic Inactivity Logout, Dynamic Certificate Generator, Email Notification Editor, JWT Authentication, XSS/CSRF/SQLi Protections.',
            'description_ar' => 'نظام إدارة تعلم (LMS) كامل يمكنك من بيع الدورات والمشاريع بدون عمولات وسطاء. احتفظ بنسبة 100% من الأرباح. أنشئ أسواقاً متعددة المدربين مع دروس Zoom المباشرة والاختبارات والشهادات والمحتوى المجدول. الميزات: دعم مدربين متعددين، Google Analytics GA4، جاهز PWA، محتوى مجدول، التحكم في أجهزة تسجيل دخول الطلاب، نظام إحالة خصم مزدوج، مصمم شهادات ديناميكي، سحب وإفلات الدروس، محرك أسئلة وأجوبة، ملفات الطلاب والمدربين، تخزين عربة التسوق في قاعدة البيانات، معاينات فيديو مباشرة، دعم YouTube وVimeo وMP4، استئناف تشغيل الفيديو، تحميل ملفات PDF/Zip، نظام مراجعة الدورات، اختبارات، مدفوعات البنوك للمدربين، بحث فوري، نظام عمولات، تكامل دروس Zoom المباشرة، عناوين URL صديقة لمحركات البحث، دعم RTL، خروج تلقائي عند عدم النشاط، منشئ شهادات ديناميكي، محرر إشعارات البريد الإلكتروني، توثيق JWT، حماية من XSS/CSRF/SQLi.',
            'price_usd' => 70000.00,
            'price_sar' => 262500.00,
            'features_en' => json_encode([
                'Multi & Public Instructor support',
                'Google Analytics GA4 integration',
                'PWA Ready',
                'Drip Content scheduling',
                'Student Login Device Control',
                'Dual-Discount Referral System',
                'Dynamic Certificate Designer',
                'Chapter/Lesson Drag & Drop',
                'Q&A Engine',
                'Zoom Live Class Integration',
                'Multi-API keys support',
                'Quizzes & Assessments',
                'Instructor Bank Payouts',
                'Commission System (Flat, Instructor-wise, Course-wise)',
                'RTL Support & SEO-friendly URLs',
                'JWT Authentication & XSS/CSRF/SQLi Protection',
            ]),
            'features_ar' => json_encode([
                'دعم المدربين المتعددين والعام',
                'تكامل Google Analytics GA4',
                'جاهز لتقنية PWA',
                'جدولة المحتوى المجدول',
                'التحكم في أجهزة تسجيل دخول الطلاب',
                'نظام إحالة خصم مزدوج',
                'مصمم شهادات ديناميكي',
                'سحب وإفلات الدروس والفصول',
                'محرك أسئلة وأجوبة',
                'تكامل دروس Zoom المباشرة',
                'دعم مفاتيح API متعددة',
                'الاختبارات والتقييمات',
                'مدفوعات البنوك للمدربين',
                'نظام العمولات (ثابت، حسب المدرب، حسب الدورة)',
                'دعم RTL وعناوين صديقة لمحركات البحث',
                'توثيق JWT وحماية XSS/CSRF/SQLi',
            ]),
            'seo_title_en' => 'Learning Management System CMS | Sell Courses & Build an LMS Platform',
            'seo_title_ar' => 'نظام إدارة التعلم | بيع الدورات وبناء منصة تعليمية',
            'seo_description_en' => 'Complete LMS script to sell courses and projects with zero commissions. Multi-instructor marketplace with Zoom classes, quizzes, certificates, drip content, and GA4 analytics.',
            'seo_description_ar' => 'نظام إدارة تعلم كامل لبيع الدورات والمشاريع بدون عمولات. سوق متعدد المدربين مع دروس Zoom والاختبارات والشهادات والمحتوى المجدول وتحليلات GA4.',
            'seo_keywords_en' => 'LMS, learning management system, sell courses online, online education platform, elearning, course marketplace, zoom integration, quizzes, certificates',
            'seo_keywords_ar' => 'نظام إدارة تعلم, LMS, بيع الدورات عبر الإنترنت, منصة تعليم إلكتروني, سوق دورات, تكامل Zoom, اختبارات, شهادات',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 4,
        ]);
    }
}
