<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $catEnterprise = Category::where('slug', 'enterprise-software')->first();
        $catEcom = Category::where('slug', 'ecommerce-solutions')->first();
        $catHr = Category::where('slug', 'hr-systems')->first();
        $catLms = Category::where('slug', 'learning-management')->first();

        // Product 1: Riof ERP
        Product::create([
            'slug' => 'riof-erp',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Riof ERP',
            'name_ar' => 'ريوف ERP',
            'description_en' => 'Comprehensive ERP system tailored for enterprise digital management. Includes core modules: Financial Accounting, Inventory Control, Supply Chain, Procurement, CRM, Analytics & BI, Role-Based Access Control (RBAC), and Audit Logging. Fully optimized for Search Engines with optimized structured data, meta tags, keyword targeting, and clean URLs.',
            'description_ar' => 'نظام تخطيط موارد المؤسسات (ERP) شامل مصمم للإدارة الرقمية للمؤسسات. يشمل الوحدات الأساسية: المحاسبة المالية، مراقبة المخزون، سلسلة التوريد، المشتريات، إدارة علاقات العملاء، التحليلات وذكاء الأعمال، التحكم في الوصول القائم على الأدوار، وتسجيل التدقيق. محسن بالكامل لمحركات البحث.',
            'price_usd' => 120000.00,
            'price_sar' => 450000.00,
            'features_en' => json_encode([
                'Financial Accounting & General Ledger',
                'Inventory Control & Warehouse Management',
                'Supply Chain & Procurement Management',
                'Customer Relationship Management (CRM)',
                'Analytics & Business Intelligence',
                'Role-Based Access Control (RBAC)',
                'Audit Logging & Compliance',
                'Multi-Currency & Multi-Language Support',
            ]),
            'features_ar' => json_encode([
                'المحاسبة المالية ودليل الحسابات العام',
                'مراقبة المخزون وإدارة المستودعات',
                'إدارة سلسلة التوريد والمشتريات',
                'إدارة علاقات العملاء',
                'التحليلات وذكاء الأعمال',
                'التحكم في الوصول القائم على الأدوار',
                'تسجيل التدقيق والامتثال',
                'دعم العملات المتعددة واللغات المتعددة',
            ]),
            'seo_title_en' => 'Riof ERP | Enterprise Digital Management System',
            'seo_title_ar' => 'ريوف ERP | نظام الإدارة الرقمية للمؤسسات',
            'seo_description_en' => 'Riof ERP is a comprehensive enterprise resource planning system with financial accounting, inventory, CRM, BI analytics, and RBAC. Optimized for digital enterprise management.',
            'seo_description_ar' => 'ريوف ERP هو نظام شامل لتخطيط موارد المؤسسات مع المحاسبة المالية والمخزون وإدارة علاقات العملاء وتحليلات ذكاء الأعمال والتحكم في الوصول.',
            'seo_keywords_en' => 'ERP, enterprise software, digital management, financial accounting, inventory control, CRM, BI analytics, RBAC, business management',
            'seo_keywords_ar' => 'ERP, برامج المؤسسات, الإدارة الرقمية, المحاسبة المالية, مراقبة المخزون, إدارة علاقات العملاء, تحليلات الأعمال',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 1,
        ]);

        // Product 2: Riof Store v-1
        Product::create([
            'slug' => 'riof-store-v1',
            'type' => 'digital',
            'category_id' => $catEcom?->id,
            'name_en' => 'Riof Store v-1',
            'name_ar' => 'ريوف ستور v-1',
            'description_en' => 'Riof Store v-1 is a Laravel Multi-Vendor eCommerce CMS. Launch a marketplace that feels structured from day one, not stitched together after launch. Riof Store gives commerce teams a practical foundation for running single-store or multi-vendor operations with connected storefront, vendor, and admin workflows. It is designed to support growth while keeping catalogue, checkout, and order flow manageable. Features: Advanced Mega Menu Builder, Ajax-based tasks, Gift Cards, Guest Checkout, Digital & Physical Product architecture, Home Page Builder, Unlimited Email Templates, Dynamic Sliders, Multi-Language (170+ languages), Multi-Currency, Order Management, Brands, Verified Reviews, Product Deals, Wishlists, Dynamic Coupons, Multi-Level Categories, Category-wise Commission Setup, Product Ratings, Gallery with Zoom, Social Login, Google reCAPTCHA, Newsletters, Product Attributes, Enterprise Security, Product Comparison, GA4 Analytics & Facebook Pixel integration, PWA Ready, One-Click Demo Import, Custom SMS Gateway integration, Messenger integration, Currency Decimal Control, Blog Engine, Product Video, Quick View, SKU Management, Unlimited Variants, Dynamic Tax/GST Calculation, Dynamic Filters, Invoice PDF Generation, Role & Permissions Engine, Up-sells & Cross-sells, Low Inventory Alerts, RTL Support, W3C Valid Markup, Bootstrap 5 UI framework.',
            'description_ar' => 'ريوف ستور v-1 هو نظام إدارة محتوى تجارة إلكترونية متعدد البائعين مبني على Laravel. أطلق سوقاً إلكترونياً منظمًا من اليوم الأول. يمنح ريوف ستور فرق التجارة أساسًا عمليًا لإدارة عمليات متجر واحد أو متعدد البائعين مع سير عمل متصل للواجهة الأمامية والبائعين والإدارة. يدعم النمو مع الحفاظ على سهولة إدارة الكتالوج وعربة التسوق والطلبات. الميزات: منشئ قوائم متقدم، مهام Ajax، بطاقات هدايا، شراء كضيف، دعم المنتجات الرقمية والمادية، منشئ صفحات رئيسية، قوالب بريد إلكتروني غير محدودة، شرائح ديناميكية، دعم 170+ لغة، عملات متعددة، إدارة الطلبات، العلامات التجارية، مراجعات موثقة، صفقات المنتجات، قوائم الرغبات، كوبونات ديناميكية، تصنيفات متعددة المستويات، عمولة حسب التصنيف، معرض مع تكبير، تسجيل اجتماعي، reCAPTCHA، النشرات البريدية، سمات المنتج، أمان مؤسسي، مقارنة المنتجات، تحليلات GA4 وفيسبوك بيكسل، PWA، استيراد تجريبي بنقرة واحدة، Gateway SMS مخصص، تكامل المراسلة، التحكم في الكسور العشرية للعملة، محرك مدونة، فيديو المنتج، عرض سريع، إدارة SKU، متغيرات غير محدودة، حساب ضريبة ديناميكي، فلاتر ديناميكية، توليد فواتير PDF، محرك الأدوار والصلاحيات، البيع الإضافي والبيع المتبادل، تنبيهات المخزون المنخفض، دعم RTL، Bootstrap 5.',
            'price_usd' => 80000.00,
            'price_sar' => 300000.00,
            'features_en' => json_encode([
                'Marketplace-ready multi-vendor architecture',
                'Vendor onboarding & seller-side management workflows',
                'Product catalogue control with browsing & cart flow',
                'Checkout & order lifecycle handling',
                'Promotion and discount tooling',
                'Admin controls for marketplace governance',
                'Advanced Mega Menu Builder',
                'Guest Checkout support',
                'Digital & Physical Product support',
                'Multi-Language (170+ languages)',
                'Multi-Currency with decimal control',
                'GA4 Analytics & Facebook Pixel integration',
                'PWA Ready',
                'Role & Permissions Engine',
                'RTL Support & Bootstrap 5 UI',
            ]),
            'features_ar' => json_encode([
                'هندسة سوق متعدد البائعين جاهزة',
                'سير عمل تأهيل البائعين وإدارة البائعين',
                'التحكم في كتالوج المنتجات مع التصفح وعربة التسوق',
                'معالجة الطلبات ودورة حياة الطلب',
                'أدوات العروض والخصم',
                'ضوابط إدارية لحوكمة السوق',
                'منشئ قوائم متقدم',
                'دعم الشراء كضيف',
                'دعم المنتجات الرقمية والمادية',
                'دعم 170+ لغة',
                'عملات متعددة مع التحكم في الكسور العشرية',
                'تكامل تحليلات GA4 وفيسبوك بيكسل',
                'جاهز لتقنية PWA',
                'محرك الأدوار والصلاحيات',
                'دعم RTL وواجهة Bootstrap 5',
            ]),
            'seo_title_en' => 'Riof Store v-1 | Multi-Vendor eCommerce CMS | Laravel Marketplace',
            'seo_title_ar' => 'ريوف ستور v-1 | نظام تجارة إلكترونية متعدد البائعين | سوق Laravel',
            'seo_description_en' => 'Riof Store v-1 is a Laravel Multi-Vendor eCommerce CMS. Launch a structured marketplace with vendor management, multi-currency, multi-language, PWA, GA4 analytics, and RTL support.',
            'seo_description_ar' => 'ريوف ستور v-1 هو نظام إدارة محتوى تجارة إلكترونية متعدد البائعين مبني على Laravel. أطلق سوقاً إلكترونياً منظماً مع إدارة البائعين والعملات المتعددة واللغات المتعددة.',
            'seo_keywords_en' => 'multi-vendor ecommerce, laravel marketplace, cms, online store, digital marketplace, ecommerce platform, multi-currency, multi-language',
            'seo_keywords_ar' => 'تجارة إلكترونية متعددة البائعين, سوق Laravel, نظام إدارة محتوى, متجر إلكتروني, سوق رقمي, منصة تجارة إلكترونية',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 2,
        ]);

        // Product 3: Riof HR v-1
        Product::create([
            'slug' => 'riof-hr-v1',
            'type' => 'digital',
            'category_id' => $catHr?->id,
            'name_en' => 'Riof HR v-1',
            'name_ar' => 'ريوف HR v-1',
            'description_en' => 'Comprehensive Human Resources & Payroll Management System. Core HR Features: Employee Self-Service (ESS) portal, Attendance & Leave Management, Biometric Device Integration support, Payroll & Payslip Generation, Department/Role Management, HR Analytics & Performance Reviews, Recruitment & Onboarding Workflows, Document Management, Expense Claims, and Activity Logging.',
            'description_ar' => 'نظام شامل لإدارة الموارد البشرية والرواتب. الميزات الأساسية: بوابة الخدمة الذاتية للموظفين، إدارة الحضور والإجازات، دعم تكامل أجهزة البصمة، إنشاء الرواتب وقسائم الراتب، إدارة الأقسام والأدوار، تحليلات الموارد البشرية ومراجعات الأداء، سير عمل التوظيف والتعيين، إدارة المستندات، مطالبات المصروفات، وتسجيل النشاطات.',
            'price_usd' => 35000.00,
            'price_sar' => 131250.00,
            'features_en' => json_encode([
                'Employee Self-Service (ESS) Portal',
                'Attendance & Leave Management',
                'Biometric Device Integration',
                'Payroll & Payslip Generation',
                'Department & Role Management',
                'HR Analytics & Performance Reviews',
                'Recruitment & Onboarding Workflows',
                'Document Management System',
                'Expense Claims Management',
                'Activity Logging & Audit Trail',
            ]),
            'features_ar' => json_encode([
                'بوابة الخدمة الذاتية للموظفين',
                'إدارة الحضور والإجازات',
                'تكامل أجهزة البصمة',
                'إنشاء الرواتب وقسائم الراتب',
                'إدارة الأقسام والأدوار',
                'تحليلات الموارد البشرية ومراجعات الأداء',
                'سير عمل التوظيف والتعيين',
                'نظام إدارة المستندات',
                'إدارة مطالبات المصروفات',
                'تسجيل النشاطات ومسار التدقيق',
            ]),
            'seo_title_en' => 'Riof HR v-1 | Human Resources & Payroll Management System',
            'seo_title_ar' => 'ريوف HR v-1 | نظام إدارة الموارد البشرية والرواتب',
            'seo_description_en' => 'Riof HR v-1 is a comprehensive HR and payroll management system with ESS portal, attendance management, biometric integration, payroll generation, and HR analytics.',
            'seo_description_ar' => 'ريوف HR v-1 هو نظام شامل لإدارة الموارد البشرية والرواتب مع بوابة الخدمة الذاتية وإدارة الحضور وتكامل البصمة وإنشاء الرواتب وتحليلات الموارد البشرية.',
            'seo_keywords_en' => 'HR software, payroll system, human resources management, employee self-service, attendance management, biometric integration, payslip generation',
            'seo_keywords_ar' => 'برامج الموارد البشرية, نظام الرواتب, إدارة الموارد البشرية, خدمة ذاتية للموظفين, إدارة الحضور, تكامل البصمة, إنشاء قسائم الراتب',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 3,
        ]);

        // Product 4: Learning Management System CMS
        Product::create([
            'slug' => 'learning-management-system-cms',
            'type' => 'digital',
            'category_id' => $catLms?->id,
            'name_en' => 'Learning Management System CMS',
            'name_ar' => 'نظام إدارة التعلم',
            'description_en' => 'Complete LMS script where you can sell courses and projects without reseller commissions. Keep 100% of profits. Setup multi-instructor marketplaces with Zoom live classes, quizzes, certificates, and drip content. Features: Multi & Public Instructor support, Google Analytics GA4, PWA Ready, Drip Content, Student Login Device Control, Dual-Discount Referral System, Dynamic Certificate Designer, Chapter/Lesson Drag & Drop positioning, Q&A Engine, Student & Instructor Profiles, Database Cart storage, Live Video Previews, Support for YouTube, Vimeo, and Self-hosted MP4s, Video Resume Playback, PDF/Zip Course Downloads, Course Query/Review system, Quizzes, Instructor Bank Payouts, Instant Search, Commission System (Flat, Instructor-wise, Course-wise), Zoom Live Class Integration with Multi-API keys, SEO-friendly plain URLs, RTL Support, Automatic Inactivity Logout, Dynamic Certificate Generator, Email Notification Editor, JWT Authentication, XSS/CSRF/SQLi Protections.',
            'description_ar' => 'نظام إدارة تعلم (LMS) كامل يمكنك من بيع الدورات والمشاريع بدون عمولات وسطاء. احتفظ بنسبة 100% من الأرباح. أنشئ أسواقاً متعددة المدربين مع دروس Zoom المباشرة والاختبارات والشهادات والمحتوى المجدول. الميزات: دعم مدربين متعددين، Google Analytics GA4، جاهز PWA، محتوى مجدول، التحكم في أجهزة تسجيل دخول الطلاب، نظام إحالة خصم مزدوج، مصمم شهادات ديناميكي، سحب وإفلات الدروس، محرك أسئلة وأجوبة، ملفات الطلاب والمدربين، تخزين عربة التسوق في قاعدة البيانات، معاينات فيديو مباشرة، دعم YouTube وVimeo وMP4، استئناف تشغيل الفيديو، تحميل ملفات PDF/Zip، نظام مراجعة الدورات، اختبارات، مدفوعات البنوك للمدربين، بحث فوري، نظام عمولات، تكامل دروس Zoom المباشرة، عناوين URL صديقة لمحركات البحث، دعم RTL، خروج تلقائي عند عدم النشاط، منشئ شهادات ديناميكي، محرر إشعارات البريد الإلكتروني، توثيق JWT، حماية من XSS/CSRF/SQLi.',
            'price_usd' => 70000.00,
            'price_sar' => 262500.00,
            'features_en' => json_encode([
                'Multi & Public Instructor support',
                'Google Analytics GA4 integration',
                'PWA Ready',
                'Drip Content scheduling',
                'Student Login Device Control',
                'Dual-Discount Referral System',
                'Dynamic Certificate Designer',
                'Chapter/Lesson Drag & Drop',
                'Q&A Engine',
                'Zoom Live Class Integration',
                'Multi-API keys support',
                'Quizzes & Assessments',
                'Instructor Bank Payouts',
                'Commission System (Flat, Instructor-wise, Course-wise)',
                'RTL Support & SEO-friendly URLs',
                'JWT Authentication & XSS/CSRF/SQLi Protection',
            ]),
            'features_ar' => json_encode([
                'دعم المدربين المتعددين والعام',
                'تكامل Google Analytics GA4',
                'جاهز لتقنية PWA',
                'جدولة المحتوى المجدول',
                'التحكم في أجهزة تسجيل دخول الطلاب',
                'نظام إحالة خصم مزدوج',
                'مصمم شهادات ديناميكي',
                'سحب وإفلات الدروس والفصول',
                'محرك أسئلة وأجوبة',
                'تكامل دروس Zoom المباشرة',
                'دعم مفاتيح API متعددة',
                'الاختبارات والتقييمات',
                'مدفوعات البنوك للمدربين',
                'نظام العمولات (ثابت، حسب المدرب، حسب الدورة)',
                'دعم RTL وعناوين صديقة لمحركات البحث',
                'توثيق JWT وحماية XSS/CSRF/SQLi',
            ]),
            'seo_title_en' => 'Learning Management System CMS | Sell Courses & Build an LMS Platform',
            'seo_title_ar' => 'نظام إدارة التعلم | بيع الدورات وبناء منصة تعليمية',
            'seo_description_en' => 'Complete LMS script to sell courses and projects with zero commissions. Multi-instructor marketplace with Zoom classes, quizzes, certificates, drip content, and GA4 analytics.',
            'seo_description_ar' => 'نظام إدارة تعلم كامل لبيع الدورات والمشاريع بدون عمولات. سوق متعدد المدربين مع دروس Zoom والاختبارات والشهادات والمحتوى المجدول وتحليلات GA4.',
            'seo_keywords_en' => 'LMS, learning management system, sell courses online, online education platform, elearning, course marketplace, zoom integration, quizzes, certificates',
            'seo_keywords_ar' => 'نظام إدارة تعلم, LMS, بيع الدورات عبر الإنترنت, منصة تعليم إلكتروني, سوق دورات, تكامل Zoom, اختبارات, شهادات',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 4,
        ]);

        // Product 6: Riof- School Management System Software
        Product::create([
            'slug' => 'riof-school-management-system',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Riof- School Management System Software',
            'name_ar' => 'ريوف - نظام إدارة المدارس',
            'description_en' => 'Riof School Management System Software. A complete solution to manage schools covering student records, staff management, attendance, exams & grades, timetables, fees & invoices, transportation, library, and parent access with multi-language and multi-branch support.',
            'description_ar' => 'ريوف - نظام إدارة المدارس. حل متكامل لإدارة المدارس يشمل سجلات الطلاب وإدارة الموظفين والحضور والامتحانات والدرجات والجداول والرسوم والفواتير والنقل والمكتبة ووصول أولياء الأمور مع دعم متعدد اللغات والفروع.',
            'price_usd' => 70000.00,
            'price_sar' => 262500.00,
            'features_en' => json_encode([
                'Student Records Management',
                'Staff Management',
                'Attendance Tracking',
                'Exams & Grades Management',
                'Timetables & Scheduling',
                'Fees & Invoice Management',
                'Parents Access Portal',
                'Multi-Language & Multi-Branch',
            ]),
            'features_ar' => json_encode([
                'إدارة سجلات الطلاب',
                'إدارة الموظفين',
                'تتبع الحضور',
                'إدارة الامتحانات والدرجات',
                'الجداول الزمنية',
                'إدارة الرسوم والفواتير',
                'بوابة وصول أولياء الأمور',
                'دعم متعدد اللغات والفروع',
            ]),
            'seo_title_en' => 'Riof School Management System | School Software',
            'seo_title_ar' => 'ريوف نظام إدارة المدارس | برنامج المدارس',
            'seo_description_en' => 'Riof School Management System software covering students, staff, attendance, exams, fees, transportation and parent access.',
            'seo_description_ar' => 'ريوف نظام إدارة المدارس يشمل الطلاب والموظفين والحضور والامتحانات والرسوم والنقل ووصول أولياء الأمور.',
            'seo_keywords_en' => 'school management system, school software, student management, education software',
            'seo_keywords_ar' => 'نظام إدارة المدارس, برنامج المدارس, إدارة الطلاب',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 6,
        ]);

        // Product 7: Online Student Registration Module for Riof
        Product::create([
            'slug' => 'online-student-registration-module-riof',
            'type' => 'digital',
            'category_id' => $catLms?->id,
            'name_en' => 'Online Student Registration Module for Riof',
            'name_ar' => 'وحدة تسجيل الطلاب عبر الإنترنت لريوف',
            'description_en' => 'Online Student Registration Module for Riof. Streamline admissions with digital online enrollment forms, document upload, application tracking, fee submission, and automated approval workflows integrated with the Riof school system.',
            'description_ar' => 'وحدة تسجيل الطلاب عبر الإنترنت لريوف. تبسيط القبول عبر نماذج تسجيل رقمية عبر الإنترنت ورفع المستندات وتتبع الطلبات وتقديم الرسوم وسير عمل موافقة تلقائي متكامل مع نظام ريوف.',
            'price_usd' => 6500.00,
            'price_sar' => 24375.00,
            'features_en' => json_encode([
                'Online Enrollment Forms',
                'Document Upload',
                'Application Tracking',
                'Online Fee Submission',
                'Automated Approval Workflows',
                'Integration with Riof School System',
            ]),
            'features_ar' => json_encode([
                'نماذج تسجيل عبر الإنترنت',
                'رفع المستندات',
                'تتبع الطلبات',
                'تقديم الرسوم عبر الإنترنت',
                'سير عمل موافقة تلقائية',
                'التكامل مع نظام ريوف',
            ]),
            'seo_title_en' => 'Online Student Registration Module for Riof | Admission Software',
            'seo_title_ar' => 'وحدة تسجيل الطلاب عبر الإنترنت لريوف | برنامج القبول',
            'seo_description_en' => 'Online Student Registration Module for Riof with enrollment forms, document upload, fee submission and automated workflows.',
            'seo_description_ar' => 'وحدة تسجيل الطلاب عبر الإنترنت لريوف مع نماذج التسجيل ورفع المستندات وتقديم الرسوم وسير العمل التلقائي.',
            'seo_keywords_en' => 'student registration, online admission, enrollment module, school registration',
            'seo_keywords_ar' => 'تسجيل الطلاب, القبول عبر الإنترنت, وحدة التسجيل',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 7,
        ]);

        // Product 8: Riof SAAS - Open Source Flutter for Android & iOS
        Product::create([
            'slug' => 'riof-saas-open-source-flutter',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Riof SAAS - Open Source Flutter for Android & iOS',
            'name_ar' => 'ريوف SAAS - كود فلاتر مفتوح لأندرويد وiOS',
            'description_en' => 'Riof SAAS - Open Source Flutter source code for Android & iOS. A fully customizable Flutter mobile application source code to build cross-platform mobile apps with native-like performance, offline support, one codebase, and seamless integration with back-end systems.',
            'description_ar' => 'ريوف SAAS - كود فلاتر مفتوح لأندرويد وiOS. كود مصدري لتطبيقات فلاتر مفتوح وقابل للتخصيص لبناء تطبيقات متوافقة مع المنصتين بأداء مشابه للتطبيقات الأصلية ودعم دون اتصال وقاعدة كود واحدة.',
            'price_usd' => 50000.00,
            'price_sar' => 187500.00,
            'features_en' => json_encode([
                'Open Source Flutter Source Code',
                'Cross-Platform (Android & iOS)',
                'Customizable UI Components',
                'Offline Support',
                'Back-end Integration Ready',
                'Native-like Performance',
            ]),
            'features_ar' => json_encode([
                'كود فلاتر مفتوح المصدر',
                'منصات متعددة (أندرويد وiOS)',
                'مكونات واجهة قابلة للتخصيص',
                'دعم العمل دون اتصال',
                'جاهز للتكامل مع الأنظمة الخلفية',
                'أداء مشابه للتطبيقات الأصلية',
            ]),
            'seo_title_en' => 'Riof SAAS Flutter Source Code | Android & iOS App',
            'seo_title_ar' => 'ريوف SAAS كود فلاتر | تطبيق أندرويد وiOS',
            'seo_description_en' => 'Riof SAAS Open Source Flutter source code to build cross-platform Android & iOS mobile apps with a single codebase.',
            'seo_description_ar' => 'ريوف SAAS كود فلاتر مفتوح لبناء تطبيقات متوافقة مع أندرويد وiOS عبر قاعدة كود واحدة.',
            'seo_keywords_en' => 'Flutter source code, open source app, Android iOS app, cross-platform mobile, mobile source code',
            'seo_keywords_ar' => 'كود فلاتر, تطبيق مفتوح, تطبيق أندرويد وiOS, تطبيقات متعددة المنصات',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 8,
        ]);

        // Product 9: Riof- School Management System Software Description
        Product::create([
            'slug' => 'riof-school-management-system-description',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Riof- School Management System Software',
            'name_ar' => 'ريوف - نظام إدارة المدارس',
            'description_en' => 'Riof School Management System Software (Description). A modular enterprise-grade platform that automates the full lifecycle of school operations including administration, academics, finance, communication, and reporting with built-in role-based access control.',
            'description_ar' => 'ريوف - نظام إدارة المدارس (الوصف). منصة معيارية بمستوى مؤسسي تعمل على أتمتة دورة العمل الكاملة لعمليات المدرسة بما في ذلك الإدارة والأكاديميات والمالية والتواصل والتقارير مع تحكم بالوصول قائم على الأدوار.',
            'price_usd' => 90000.00,
            'price_sar' => 337500.00,
            'features_en' => json_encode([
                'Full School Lifecycle Automation',
                'Administration Management',
                'Finance & Accounting',
                'Communication Tools',
                'Reporting & Analytics',
                'Role-Based Access Control',
            ]),
            'features_ar' => json_encode([
                'أتمتة دورة عمل المدرسة الكاملة',
                'إدارة الشؤون الإدارية',
                'المالية والمحاسبة',
                'أدوات التواصل',
                'التقارير والتحليلات',
                'التحكم بالوصول حسب الأدوار',
            ]),
            'seo_title_en' => 'Riof School Management System | School Automation Software',
            'seo_title_ar' => 'ريوف نظام إدارة المدارس | برنامج الأتمتة المدرسية',
            'seo_description_en' => 'Riof School Management System software automating administration, academics, finance and reporting with RBAC.',
            'seo_description_ar' => 'ريوف نظام إدارة المدارس يعمل على أتمتة الإدارة والأكاديميات والمالية والتقارير مع تحكم بالوصول.',
            'seo_keywords_en' => 'school automation, school management, education software, school ERP',
            'seo_keywords_ar' => 'أتمتة المدارس, إدارة المدارس, برنامج المدارس',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 9,
        ]);

        // Product 10: Theem | Riof Laravel Ecommerce System CMS Module
        Product::create([
            'slug' => 'theem-riof-ecommerce-module',
            'type' => 'digital',
            'category_id' => $catEcom?->id,
            'name_en' => 'Theem | Riof Laravel Ecommerce System CMS Module',
            'name_ar' => 'ثيرم | وحدة نظام التجارة الإلكترونية لريوف',
            'description_en' => 'Theem | Riof Laravel Ecommerce System CMS Module. Theem adds theme-management capabilities to the Riof eCommerce CMS, enabling easy storefront theming, template customization, and a drag-and-drop layout builder for a fully branded storefront.',
            'description_ar' => 'ثيرم | وحدة نظام التجارة الإلكترونية لريوف. تضيف ثيرم إمكانيات إدارة الثيمات إلى نظام التجارة الإلكترونية لريوف، مما يتيح تخصيص واجهات المتجر والقوالب ومنشئ تخطيط بالسحب والإفلات.',
            'price_usd' => 4900.00,
            'price_sar' => 18375.00,
            'features_en' => json_encode([
                'Theme Management System',
                'Storefront Customization',
                'Template Customization',
                'Drag & Drop Layout Builder',
                'Branded Storefront Support',
            ]),
            'features_ar' => json_encode([
                'نظام إدارة الثيمات',
                'تخصيص واجهة المتجر',
                'تخصيص القوالب',
                'منشئ تخطيط بالسحب والإفلات',
                'دعم واجهة متجر ذات هوية',
            ]),
            'seo_title_en' => 'Theem Module | Riof Laravel Ecommerce Theme System',
            'seo_title_ar' => 'وحدة ثيرم | نظام ثيمات التجارة الإلكترونية لريوف',
            'seo_description_en' => 'Theem module adds theme management and drag-and-drop layout building to the Riof Laravel eCommerce CMS.',
            'seo_description_ar' => 'وحدة ثيرم تضيف إدارة الثيمات ومنشئ التخطيط إلى نظام التجارة الإلكترونية لريوف.',
            'seo_keywords_en' => 'ecommerce theme, Laravel module, theme builder, storefront customization',
            'seo_keywords_ar' => 'ثيم التجارة الإلكترونية, وحدة Laravel, منشئ الثيمات',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 10,
        ]);

        // Product 11: sslcommerz | Riof Laravel Ecommerce System CMS Module
        Product::create([
            'slug' => 'sslcommerz-riof-ecommerce-module',
            'type' => 'digital',
            'category_id' => $catEcom?->id,
            'name_en' => 'sslcommerz | Riof Laravel Ecommerce System CMS Module',
            'name_ar' => 'sslcommerz | وحدة نظام التجارة الإلكترونية لريوف',
            'description_en' => 'sslcommerz | Riof Laravel Ecommerce System CMS Module. Enables secure payment gateway integration with SSLCommerz payment processing, supporting card payments, mobile banking, and payment status verification for the Riof eCommerce system.',
            'description_ar' => 'sslcommerz | وحدة نظام التجارة الإلكترونية لريوف. تتيح الدمج الآمن مع بوابة الدفع SSLCommerz لدعم مدفوعات البطاقات والخدمات المصرفية عبر الهاتف والتحقق من حالة الدفع لنظام ريوف.',
            'price_usd' => 4900.00,
            'price_sar' => 18375.00,
            'features_en' => json_encode([
                'SSLCommerz Payment Gateway Integration',
                'Card Payments Support',
                'Mobile Banking Support',
                'Payment Status Verification',
                'Secure Transaction Processing',
            ]),
            'features_ar' => json_encode([
                'دمج بوابة دفع SSLCommerz',
                'دعم مدفوعات البطاقات',
                'دعم الخدمات المصرفية عبر الهاتف',
                'التحقق من حالة الدفع',
                'معالجة آمنة للمعاملات',
            ]),
            'seo_title_en' => 'sslcommerz Module | Riof Laravel Ecommerce Payment Gateway',
            'seo_title_ar' => 'وحدة sslcommerz | بوابة دفع ريوف للتجارة الإلكترونية',
            'seo_description_en' => 'sslcommerz module integrates SSLCommerz payment processing into the Riof Laravel eCommerce CMS.',
            'seo_description_ar' => 'وحدة sslcommerz تدمج معالجة مدفوعات SSLCommerz في نظام ريوف للتجارة الإلكترونية.',
            'seo_keywords_en' => 'SSLCommerz, payment gateway, Laravel ecommerce, payment module',
            'seo_keywords_ar' => 'SSLCommerz, بوابة دفع, تجارة إلكترونية Laravel',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 11,
        ]);

        // Product 12: Calendar - Riof Module
        Product::create([
            'slug' => 'riof-calendar-module',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Calendar - Riof Module',
            'name_ar' => 'التقويم - وحدة ريوف',
            'description_en' => 'Calendar - Riof Module. A comprehensive calendar and scheduling module with events, appointments, reminders, recurring events, and shared team calendars to organize academic, administrative, and business schedules.',
            'description_ar' => 'التقويم - وحدة ريوف. وحدة تقويم وجدولة شاملة مع أحداث ومواعيد وتذكيرات وأحداث متكررة وتقاويم فريق مشتركة لتنظيم الجداول الأكاديمية والإدارية والأعمال.',
            'price_usd' => 10000.00,
            'price_sar' => 37500.00,
            'features_en' => json_encode([
                'Events & Appointments',
                'Recurring Events',
                'Reminders & Notifications',
                'Shared Team Calendars',
                'Scheduling Management',
            ]),
            'features_ar' => json_encode([
                'الأحداث والمواعيد',
                'الأحداث المتكررة',
                'التذكيرات والإشعارات',
                'تقاويم الفريق المشتركة',
                'إدارة الجدولة',
            ]),
            'seo_title_en' => 'Calendar Module | Riof Scheduling System',
            'seo_title_ar' => 'وحدة التقويم | نظام الجدولة لريوف',
            'seo_description_en' => 'Riof Calendar module with events, appointments, reminders and shared team calendars for scheduling.',
            'seo_description_ar' => 'وحدة تقويم ريوف مع الأحداث والمواعيد والتذكيرات وتقاويم الفريق المشتركة.',
            'seo_keywords_en' => 'calendar module, scheduling, events, appointments, reminders',
            'seo_keywords_ar' => 'وحدة تقويم, جدولة, أحداث, مواعيد, تذكيرات',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 12,
        ]);

        // Product 13: Aymakan - Riof Module
        Product::create([
            'slug' => 'riof-aymakan-module',
            'type' => 'digital',
            'category_id' => $catEcom?->id,
            'name_en' => 'Aymakan - Riof Module',
            'name_ar' => 'أيمكان - وحدة ريوف',
            'description_en' => 'Aymakan - Riof Module. It works with amazcart Single and multi-vendor. Adds Aymakan shipping/delivery integration enabling real-time shipping rates, order tracking, and logistics management for single and multi-vendor storefronts.',
            'description_ar' => 'أيمكان - وحدة ريوف. تعمل مع amazcart للمتاجر الفردية ومتعددة البائعين. تضيف تكامل الشحن والتوصيل من أيمكان لتفعيل أسعار الشحن المباشرة وتتبع الطلبات وإدارة اللوجستيات.',
            'price_usd' => 9900.00,
            'price_sar' => 37125.00,
            'features_en' => json_encode([
                'Aymakan Shipping & Delivery Integration',
                'Real-time Shipping Rates',
                'Order Tracking',
                'Logistics Management',
                'Works with Single & Multi-vendor (amazcart)',
            ]),
            'features_ar' => json_encode([
                'تكامل شحن وتوصيل أيمكان',
                'أسعار شحن مباشرة',
                'تتبع الطلبات',
                'إدارة اللوجستيات',
                'يعمل مع المتاجر الفردية ومتعددة البائعين',
            ]),
            'seo_title_en' => 'Aymakan Module | Riof Shipping & Delivery Integration',
            'seo_title_ar' => 'وحدة أيمكان | تكامل الشحن والتوصيل لريوف',
            'seo_description_en' => 'Aymakan module adds real-time shipping rates, tracking and logistics to amazcart single and multi-vendor stores.',
            'seo_description_ar' => 'وحدة أيمكان تضيف أسعار الشحن المباشرة والتتبع واللوجستيات لمتاجر amazcart.',
            'seo_keywords_en' => 'Aymakan, shipping integration, delivery module, logistics',
            'seo_keywords_ar' => 'أيمكان, تكامل الشحن, وحدة التوصيل, لوجستيات',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 13,
        ]);

        // Product 14: Riof SAAS Bundle - School Management System Software
        Product::create([
            'slug' => 'riof-saas-bundle-school-management',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'Riof SAAS Bundle - School Management System Software',
            'name_ar' => 'حزمة ريوف SAAS - نظام إدارة المدارس',
            'description_en' => 'RiofEdu SAAS Bundle, Included RiofEdu Single School, SAAS Module, Online Registration, and Flutter source code. A complete SaaS-ready bundle to run a school management platform with single-school deployments, SAAS multi-tenant capability, online student registration, and Flutter mobile source code.',
            'description_ar' => 'حزمة ريوف SAAS، تشمل مدرسة واحد ووحدة SAAS والتسجيل عبر الإنترنت وكود فلاتر. حزمة كاملة جاهزة للنظام كخدمة لإدارة المدارس مع نشر لعدة مستأجرين وتسجيل طلاب وفلترة.',
            'price_usd' => 40000.00,
            'price_sar' => 150000.00,
            'features_en' => json_encode([
                'RiofEdu Single School',
                'SAAS Multi-Tenant Module',
                'Online Registration',
                'Flutter Source Code',
                'Complete SaaS-ready Bundle',
            ]),
            'features_ar' => json_encode([
                'مدرسة ريوف التعليمية الواحدة',
                'وحدة SAAS متعددة المستأجرين',
                'التسجيل عبر الإنترنت',
                'كود فلاتر',
                'حزمة كاملة جاهزة للنظام كخدمة',
            ]),
            'seo_title_en' => 'Riof SAAS Bundle | School Management System Software',
            'seo_title_ar' => 'حزمة ريوف SAAS | نظام إدارة المدارس',
            'seo_description_en' => 'RiofEdu SAAS Bundle includes single school, SAAS module, online registration and Flutter source code for a complete school platform.',
            'seo_description_ar' => 'حزمة ريوف SAAS تشمل مدرسة ووحدة SAAS وتسجيل عبر الإنترنت وكود فلاتر لمنصة مدارس كاملة.',
            'seo_keywords_en' => 'school management, SAAS bundle, education platform, Flutter source, online registration',
            'seo_keywords_ar' => 'إدارة المدارس, حزمة SAAS, منصة التعليم, كود فلاتر',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 14,
        ]);

        // Product 15: Forum - Riof LMS Module
        Product::create([
            'slug' => 'riof-forum-lms-module',
            'type' => 'digital',
            'category_id' => $catLms?->id,
            'name_en' => 'Forum - Riof LMS Module',
            'name_ar' => 'المنتدى - وحدة ريوف LMS',
            'description_en' => 'Forum - Riof LMS Module. Adds a rich discussion forum to the Riof Learning Management System for course discussions, Q&A, community engagement, threads, upvotes, and moderation tools to boost learner interaction.',
            'description_ar' => 'المنتدى - وحدة ريوف LMS. يضيف منتدى نقاش غني لنظام إدارة التعلم لريوف لمناقشات الدورات والأسئلة والأجوبة وتفاعل المجتمع والمواضيع والتصويت وأدوات الإشراف لتعزيز تفاعل المتعلمين.',
            'price_usd' => 12000.00,
            'price_sar' => 45000.00,
            'features_en' => json_encode([
                'Discussion Forum',
                'Course Discussions & Q&A',
                'Threads & Replies',
                'Upvotes & Ratings',
                'Moderation Tools',
                'Community Engagement',
            ]),
            'features_ar' => json_encode([
                'منتدى نقاش',
                'مناقشات الدورات والأسئلة والأجوبة',
                'المواضيع والردود',
                'التصويت والتقييم',
                'أدوات الإشراف',
                'تفاعل المجتمع',
            ]),
            'seo_title_en' => 'Forum Module | Riof LMS Discussion Community',
            'seo_title_ar' => 'وحدة المنتدى | مجتمع نقاش ريوف LMS',
            'seo_description_en' => 'Riof Forum LMS module adds discussions, threads, upvotes and moderation to boost learner engagement.',
            'seo_description_ar' => 'وحدة منتدى ريوف LMS تضيف المناقشات والمواضيع والتصويت والإشراف لتعزيز تفاعل المتعلمين.',
            'seo_keywords_en' => 'forum module, LMS forum, discussion board, Q&A, community',
            'seo_keywords_ar' => 'وحدة منتدى, منتدى LMS, لوحة نقاش, أسئلة وأجوبة',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 15,
        ]);

        // Product 16: RiofBiometrics Desktop Application Description
        Product::create([
            'slug' => 'riof-biometrics-desktop-application',
            'type' => 'digital',
            'category_id' => $catHr?->id,
            'name_en' => 'RiofBiometrics Desktop Application',
            'name_ar' => 'تطبيق ريوف للبصمة المكتبي',
            'description_en' => 'RiofBiometrics Desktop Application. A desktop attendance application that connects biometric devices to the attendance management system, enabling fingerprint/face recognition clock-in, real-time attendance sync, and integration with payroll.',
            'description_ar' => 'تطبيق ريوف للبصمة المكتبي. تطبيق حضور مكتبي يربط أجهزة البصمة بنظام إدارة الحضور، مع دعم بصمة/تعرف الوجه وتسجيل الحضور لمزامنة فورية وتكامل مع الرواتب.',
            'price_usd' => 149900.00,
            'price_sar' => 562125.00,
            'features_en' => json_encode([
                'Biometric Device Integration',
                'Fingerprint & Face Recognition',
                'Clock-in / Clock-out Tracking',
                'Real-time Attendance Sync',
                'Payroll Integration',
            ]),
            'features_ar' => json_encode([
                'تكامل أجهزة البصمة',
                'البصمة والتعرف على الوجه',
                'تتبع الحضور والانصراف',
                'مزامنة الحضور الفورية',
                'التكامل مع الرواتب',
            ]),
            'seo_title_en' => 'RiofBiometrics Desktop Application | Biometric Attendance',
            'seo_title_ar' => 'تطبيق ريوف للبصمة المكتبي | حضور بالبصمة',
            'seo_description_en' => 'RiofBiometrics desktop app connects biometric devices for fingerprint attendance, real-time sync and payroll integration.',
            'seo_description_ar' => 'تطبيق ريوف للبصمة يربط أجهزة البصمة لحضور عبر البصمة ومزامنة فورية وتكامل مع الرواتب.',
            'seo_keywords_en' => 'biometrics, desktop application, fingerprint attendance, face recognition',
            'seo_keywords_ar' => 'بصمة, تطبيق مكتبي, حضور بالبصمة, تعرف الوجه',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 16,
        ]);

        // Product 17: RiofAdvocate - Lawyer Office Management System
        Product::create([
            'slug' => 'riof-advocate-lawyer-office-management',
            'type' => 'digital',
            'category_id' => $catEnterprise?->id,
            'name_en' => 'RiofAdvocate - Lawyer Office Management System with Case, Client & Appointment Tracking',
            'name_ar' => 'ريوف المستشار - نظام إدارة مكاتب المحاماة مع تتبع القضايا والعملاء والمواعيد',
            'description_en' => 'RiofAdvocate - Lawyer Office Management System with Case, Client & Appointment Tracking. A dedicated software for law offices to manage cases, clients, appointments, hearings, documents, billing, and reminders with full calendar and reporting.',
            'description_ar' => 'ريوف المستشار - نظام إدارة مكاتب المحاماة مع تتبع القضايا والعملاء والمواعيد. برنامج مخصص لمكاتب المحاماة لإدارة القضايا والعملاء والمواعيد والجلسات والمستندات والفوترة والتذكيرات مع تقويم وتقارير كاملة.',
            'price_usd' => 16000.00,
            'price_sar' => 60000.00,
            'features_en' => json_encode([
                'Case Management',
                'Client Tracking',
                'Appointment Scheduling',
                'Hearings Management',
                'Document Management',
                'Billing & Invoicing',
                'Reminders & Calendar',
                'Reporting & Analytics',
            ]),
            'features_ar' => json_encode([
                'إدارة القضايا',
                'تتبع العملاء',
                'جدولة المواعيد',
                'إدارة الجلسات',
                'إدارة المستندات',
                'الفوترة وإصدار الفواتير',
                'التذكيرات والتقويم',
                'التقارير والتحليلات',
            ]),
            'seo_title_en' => 'RiofAdvocate | Lawyer Office Management System',
            'seo_title_ar' => 'ريوف المستشار | نظام إدارة مكاتب المحاماة',
            'seo_description_en' => 'RiofAdvocate lawyer office management system for cases, clients, appointments, hearings, billing and reporting.',
            'seo_description_ar' => 'ريوف المستشار نظام إدارة مكاتب المحاماة للقضايا والعملاء والمواعيد والجلسات والفوترة والتقارير.',
            'seo_keywords_en' => 'lawyer management, legal case management, lawyer office software, law firm CRM',
            'seo_keywords_ar' => 'إدارة المحامي, إدارة القضايا القانونية, برنامج مكاتب المحاماة',
            'schema_type' => 'SoftwareApplication',
            'is_active' => true,
            'sort_order' => 17,
        ]);
    }
}
